language: node_js
node_js: "stable"
services:
    - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres

env: 
    global:
        - DB_HOSTNAME="localhost"
        - DB_PASSWORD=""
        - DB_USERNAME="postgres"
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
install:
    - nvm install node
    - node -v
    - npm i -g yarn
    - yarn

before_deploy:
    # Install Google Cloud SDK
    - curl https://sdk.cloud.google.com | bash > /dev/null
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud --quiet version
    - gcloud --quiet components update
    
    # Retrieve Credentials (Replace next file with result from travis encrypt-files)
    - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
    - tar -xf secrets.tar

    # Authenticate to Google Cloud
    - gcloud auth activate-service-account --key-file ./secrets/google-api-key.json

deploy:
    provider: script
    skip_cleanup: true
    # Replace the project name here
    script: yarn deploy --project cs3219-otot-b-293610
    on:
        branch: main